"""empty message

Revision ID: 90849f50ae6f
Revises: b96c3b31fe1d
Create Date: 2020-01-03 21:58:23.556670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90849f50ae6f'
down_revision = 'b96c3b31fe1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
