"""empty message

Revision ID: 9572fe4d0acc
Revises: 90849f50ae6f
Create Date: 2020-01-03 22:12:14.088361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9572fe4d0acc'
down_revision = '90849f50ae6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='genres::character varying[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
